/*
 * Simple Inventory API
 * This is Gary's pet api
 *
 * OpenAPI spec version: 1.0.0
 * Contact: gary258796@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.Pet;
import org.junit.Assert;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DevelopersApi
 */
@Ignore
public class DevelopersApiTest {

    private final DevelopersApi api = new DevelopersApi();

    
    /**
     * search by name and age.
     *
     * Return all pets with input name and age. If no input, return all pet by default. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchAllPetsTest() throws ApiException {
        String petName = null;
        Integer age = null;
        List<Pet> response = api.searchAllPets(petName, age);
        Assert.assertEquals(response.size(), 3);
    }
    
}
