/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.21).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2021-08-18T16:39:44.865Z")

@Validated
@Api(value = "pet")
public interface PetApi {

    @ApiOperation(value = "add a new pet", nickname = "addPet", notes = "Add new pet to system", tags={ "pet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "pet added"),
        @ApiResponse(code = 400, message = "Invalid opearation. Add failed."),
        @ApiResponse(code = 409, message = "A pet with that name and age already exists") })
    @RequestMapping(value = "/pet",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addPet(@NotNull @ApiParam(value = "The name of the new pet", required = true) @Valid @RequestParam(value = "petName", required = true) String petName,@NotNull @Min(0) @Max(30) @ApiParam(value = "The age of the new pet", required = true) @Valid @RequestParam(value = "age", required = true) Integer age);

}
